import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import App from './App'

describe('APEX site', () => {
  beforeEach(() => localStorage.clear())
  it('renders the main content and services', () => {
    render(<App />)
    expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('Автомобиль')
    expect(screen.getAllByText('Детейлинг-мойка').length).toBeGreaterThan(0)
    expect(screen.getByText('Porsche 911 Carrera')).toBeInTheDocument()
    expect(screen.getAllByRole('link', { name: companyPhone })[0]).toHaveAttribute('href', 'tel:+79991234567')
  })
  it('switches real before and after examples for every service', async () => {
    const user=userEvent.setup();render(<App />)
    expect(screen.getByText(/Porsche Taycan · Без дорожного налёта/)).toBeInTheDocument()
    await user.click(screen.getByRole('tab',{name:/Полировка кузова/}))
    expect(screen.getByText(/Чёрный лак · Убрали сетку царапин/)).toBeInTheDocument()
    expect(screen.getByAltText('Полировка кузова: состояние до работ')).toHaveAttribute('src','/images/comparisons/polish-before.webp')
  })
  it('opens and closes the mobile menu', async () => {
    const user = userEvent.setup(); render(<App />)
    await user.click(screen.getByLabelText('Открыть меню'))
    expect(screen.getByLabelText('Мобильная навигация').parentElement).toHaveClass('is-open')
    await user.click(screen.getByLabelText('Закрыть меню'))
    expect(screen.getByLabelText('Мобильная навигация').parentElement).not.toHaveClass('is-open')
  })
  it('validates and submits lead form', async () => {
    const user = userEvent.setup(); render(<App />)
    const submit = screen.getByRole('button', { name: /Получить расчёт/ })
    await user.click(submit)
    expect(screen.getByText('Укажите, как к вам обращаться')).toBeInTheDocument()
    expect(screen.getByText(/Введите номер полностью/)).toBeInTheDocument()
    await user.type(screen.getByLabelText(/Ваше имя/), 'Антон')
    const phone=screen.getByRole('textbox',{name:/^Телефон/})
    await user.type(phone, '7')
    expect(phone).toHaveValue('+7 ')
    await user.clear(phone)
    await user.type(phone, '123')
    expect(phone).toHaveValue('+7 (123)')
    await user.click(submit)
    expect(screen.getByText(/Введите номер полностью/)).toBeInTheDocument()
    await user.clear(phone); await user.type(phone, '+7 999 555-44-33')
    await user.click(submit)
    expect(await screen.findByText('Заявка принята')).toBeInTheDocument()
    expect(localStorage.getItem('apex-leads')).toContain('Антон')
  })
  it('changes country code and formats an international phone', async () => {
    const user=userEvent.setup();render(<App />)
    await user.selectOptions(screen.getByRole('combobox',{name:'Страна и телефонный код'}),'BY')
    const phone=screen.getByRole('textbox',{name:/^Телефон/})
    expect(phone).toHaveAttribute('placeholder','+375 (29) 123-45-67')
    await user.type(phone,'291234567')
    expect(phone).toHaveValue('+375 (29) 123-45-67')
  })
  it('opens legal modal and closes it with Escape', async () => {
    const user=userEvent.setup();render(<App />)
    await user.click(screen.getByRole('button',{name:'Политика конфиденциальности'}))
    expect(screen.getByRole('dialog')).toBeInTheDocument()
    fireEvent.keyDown(window,{key:'Escape'})
    await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
  })
  it('shows an interactive map with a link to Yandex Maps', () => {
    render(<App />)
    expect(screen.getByTitle('Интерактивная карта проезда к APEX DETAILING')).toHaveAttribute('src',expect.stringContaining('yandex.ru/map-widget'))
    expect(screen.getByRole('link',{name:'Открыть карту в Яндекс Картах'})).toHaveAttribute('href',expect.stringContaining('yandex.ru/maps'))
    expect(screen.getByRole('link',{name:'Открыть карту в Яндекс Картах'})).toHaveAttribute('target','_blank')
  })
})
const companyPhone = '+7 (999) 123-45-67'
