import { useEffect, useState } from 'react'
import { ArrowRight, ChevronLeft, ChevronRight, Clock3, ExternalLink, MapPin, Menu, Phone, Sparkles, Star, X } from 'lucide-react'
import './styles.css'

const BOOKING='https://dikidi.net/1064854', VK='https://vk.ru/beautyprostranstvoklg', PHONE='+7 (962) 370-12-11'
const nav=[['Главная','home'],['Услуги','services'],['Работы','works'],['О нас','about'],['Контакты','contacts']] as const
const services=[
 {title:'Волосы',text:'Стрижки, окрашивания, укладки и профессиональные уходы.',price:'стрижка от 2 500 ₽',image:'beauty/photo-5.jpg'},
 {title:'Маникюр & педикюр',text:'Точная архитектура, бережная обработка и стойкое покрытие.',price:'по записи',image:'beauty/gallery-6.jpg'},
 {title:'Уходы',text:'Ботокс, нанопластика, кератин и восстановление структуры волос.',price:'от 2 000 ₽',image:'beauty/gallery-1.jpg'},
 {title:'Образ',text:'Макияж и укладка для события, съёмки или важного вечера.',price:'по записи',image:'beauty/gallery-4.jpg'}]
const works=[
 {image:'beauty/photo-5.jpg',label:'Окрашивание & укладка',wide:true},{image:'beauty/gallery-1.jpg',label:'Тотальный блонд'},
 {image:'beauty/gallery-2.jpg',label:'Зеркальное полотно'},{image:'beauty/gallery-3.jpg',label:'Холодный блонд'},
 {image:'beauty/gallery-4.jpg',label:'Вечерняя укладка',wide:true},{image:'beauty/gallery-5.jpg',label:'Френч'},
 {image:'beauty/gallery-6.jpg',label:'Дизайн ногтей'},{image:'beauty/gallery-7.jpg',label:'Маникюр'},
 {image:'beauty/gallery-8.jpg',label:'Работа мастера',wide:true},{image:'beauty/gallery-11.jpg',label:'Гладкость и блеск'},
 {image:'beauty/gallery-12.jpg',label:'Педикюр'},{image:'beauty/photo-1.jpg',label:'Интерьер',wide:true}]
const reviews=[
 ['«Из раза в раз — прекрасный результат. Здесь я поняла, что нашла своё место и своего мастера.»','Екатерина Б.'],
 ['«Стильный интерьер, доброжелательные девушки и стабильно отличная работа мастера.»','Ксения К.'],
 ['«Помогли сформировать образ для фотосессии — макияж и укладка получились именно такими, как хотелось.»','Елена Е.']]

function Logo(){return <button className="logo" onClick={()=>window.location.reload()} aria-label="Перезагрузить сайт"><span className="logo-orbit">B</span><span><b>BEAUTY</b><small>ПРОСТРАНСТВО</small></span></button>}
function Booking({dark=false}:{dark?:boolean}){return <a className={`pill ${dark?'pill-dark':''}`} href={BOOKING} target="_blank" rel="noreferrer">Записаться <ArrowRight size={17}/></a>}
function Header({page,setPage}:{page:string,setPage:(p:string)=>void}){
 const [open,setOpen]=useState(false); const go=(p:string)=>{setPage(p);setOpen(false);window.scrollTo({top:0,behavior:'smooth'})}
 return <header><Logo/><nav>{nav.map(([label,id])=><button className={page===id?'active':''} key={id} onClick={()=>go(id)}>{label}</button>)}</nav><Booking dark/><button className="menu" onClick={()=>setOpen(true)} aria-label="Открыть меню"><Menu/></button>
 {open&&<div className="mobile"><div><Logo/><button onClick={()=>setOpen(false)} aria-label="Закрыть меню"><X/></button></div>{nav.map(([label,id],i)=><button key={id} onClick={()=>go(id)}><small>0{i+1}</small>{label}<ArrowRight/></button>)}<Booking/></div>}</header>}
function Hero({go}:{go:(p:string)=>void}){return <main className="hero page-enter"><div className="hero-copy"><div className="kicker"><span/> BEAUTY ПРОСТРАНСТВО · КАЛУГА</div><h1>Красота,<br/>в которой <em>вы.</em></h1><p>Современный салон в центре Калуги — про внимание к деталям, уверенность в мастере и удовольствие от каждой встречи с собой.</p><div className="hero-actions"><Booking/><button onClick={()=>go('works')}>Смотреть работы <ArrowRight/></button></div><div className="hero-proof"><strong>4,7</strong><span><i><Star/><Star/><Star/><Star/><Star/></i>55 отзывов на Яндекс</span><span>Проверено владельцем</span></div></div><div className="hero-visual"><img src="beauty/photo-5.jpg" alt="Работа мастера Beauty Пространство"/><div className="hero-glow"/><div className="float-card"><Sparkles/><span><b>Ваш образ</b><small>точно про вас</small></span></div><div className="float-number">01</div></div></main>}
function Home({go}:{go:(p:string)=>void}){return <><Hero go={go}/><section className="marquee"><div>ВОЛОСЫ • НОГТИ • МАКИЯЖ • УХОД • <span>ВОЛОСЫ • НОГТИ • МАКИЯЖ • УХОД •</span></div></section><section className="facts"><div><strong>131</strong><span>оценка гостей</span></div><div><strong>111</strong><span>фото в портфолио</span></div><div><strong>7/7</strong><span>работаем ежедневно</span></div><div><strong>94%</strong><span>отмечают атмосферу</span></div></section><section className="teaser"><div><div className="kicker dark"><span/> ПРОСТРАНСТВО ЗАБОТЫ</div><h2>Здесь красота<br/><em>чувствуется.</em></h2></div><p>Сильные мастера, эстетичный интерьер и спокойный сервис. Всё, чтобы после визита вы унесли с собой не только результат, но и особое состояние.</p><button onClick={()=>go('about')}>Узнать о нас <ArrowRight/></button></section><section className="home-grid">{services.slice(0,3).map((s,i)=><article key={s.title} onClick={()=>go('services')}><img src={s.image} alt={s.title}/><span>0{i+1}</span><div><h3>{s.title}</h3><p>{s.text}</p></div></article>)}</section></>}
function Services(){return <main className="inner page-enter"><div className="inner-head"><div className="kicker dark"><span/> МЕНЮ УСЛУГ</div><h1>Всё для вашего<br/><em>особенного образа.</em></h1><p>Точные техники, профессиональные составы и рекомендации, которые подходят именно вам.</p></div><div className="service-list">{services.map((s,i)=><article key={s.title}><div className="service-index">0{i+1}</div><img src={s.image} alt={s.title}/><div><h2>{s.title}</h2><p>{s.text}</p><strong>{s.price}</strong></div><a href={BOOKING} target="_blank" rel="noreferrer" aria-label={`Записаться: ${s.title}`}><ArrowRight/></a></article>)}</div><section className="popular"><div className="kicker dark"><span/> ПОПУЛЯРНО СЕЙЧАС</div><div className="popular-grid"><article><small>01</small><h3>Горячий ботокс / коллаген</h3><b>4 500 ₽</b></article><article><small>02</small><h3>Холодный ботокс</h3><b>2 000 ₽</b></article><article><small>03</small><h3>Нанопластика волос</h3><b>6 000 ₽</b></article><article><small>04</small><h3>Глянцевый кератин</h3><b>5 000 ₽</b></article></div></section><div className="price-note"><span>Актуальная стоимость</span><p>Итоговая цена зависит от длины волос, выбранной техники и объёма работы. Мастер уточнит всё до начала процедуры.</p><Booking dark/></div></main>}
function Works(){const [active,setActive]=useState<number|null>(null);return <main className="inner page-enter"><div className="inner-head split"><div><div className="kicker dark"><span/> РЕАЛЬНЫЕ РАБОТЫ</div><h1>Результаты,<br/><em>которые говорят сами.</em></h1></div><p>Фотографии салона и работ из открытой галереи Beauty Пространство. Нажмите, чтобы рассмотреть.</p></div><div className="gallery">{works.map((w,i)=><button className={w.wide?'wide':''} key={w.image} onClick={()=>setActive(i)}><img src={w.image} alt={w.label}/><span>0{i+1}</span><h3>{w.label}</h3><i><ExternalLink/></i></button>)}</div><a className="vk-line" href={VK} target="_blank" rel="noreferrer"><span>Больше свежих работ — в сообществе VK</span><ArrowRight/></a>{active!==null&&<div className="lightbox" onClick={e=>e.target===e.currentTarget&&setActive(null)}><button onClick={()=>setActive(null)}><X/></button><img src={works[active].image} alt={works[active].label}/><p>{works[active].label}</p></div>}</main>}
function About(){return <main className="inner page-enter"><div className="about-hero"><img src="beauty/photo-1.jpg" alt="Интерьер Beauty Пространство"/><div><div className="kicker"><span/> О BEAUTY ПРОСТРАНСТВО</div><h1>Место, где<br/><em>легко быть собой.</em></h1><p>Мы верим, что хороший бьюти‑сервис начинается с диалога. Сначала слышим вас, затем подбираем решение — бережно, честно и со вкусом.</p></div></div><section className="values"><article><span>01</span><h2>Мастерство</h2><p>Внимание к нюансам и техники, которым можно доверять.</p></article><article><span>02</span><h2>Атмосфера</h2><p>Зелень, мягкий свет и спокойствие — пространство без суеты.</p></article><article><span>03</span><h2>Индивидуальность</h2><p>Не меняем вас. Подчеркиваем то, что уже прекрасно.</p></article></section><Reviews/></main>}
function Reviews(){const [n,setN]=useState(0);return <section className="reviews"><div><div className="kicker dark"><span/> ГОСТИ О НАС</div><h2>Доверие —<br/><em>лучшая рекомендация.</em></h2><div className="review-controls"><button onClick={()=>setN((n+reviews.length-1)%reviews.length)}><ChevronLeft/></button><button onClick={()=>setN((n+1)%reviews.length)}><ChevronRight/></button></div></div><article><div className="stars">★★★★★</div><blockquote>{reviews[n][0]}</blockquote><b>{reviews[n][1]}</b><small>Отзыв гостя салона</small></article></section>}
function Contacts(){return <main className="contacts page-enter"><div className="contact-copy"><div className="kicker"><span/> КОНТАКТЫ</div><h1>Будем рады<br/><em>видеть вас.</em></h1><p>Выберите удобное время онлайн или напишите нам в VK. Подскажем по услугам и поможем определиться.</p><Booking/><div className="contact-items"><a href="tel:+79623701211"><Phone/><span><small>Телефон</small>{PHONE}</span></a><div><Clock3/><span><small>Режим работы</small>Ежедневно, 10:00–19:00</span></div><a href="https://yandex.ru/maps/?text=Калуга%20Достоевского%2034" target="_blank" rel="noreferrer"><MapPin/><span><small>Адрес</small>Калуга, ул. Достоевского, 34, 2 этаж</span></a></div></div><div className="contact-image"><img src="beauty/photo-3.jpg" alt="Вывеска Beauty Пространство"/><div><span>BEAUTY</span><small>ПРОСТРАНСТВО</small></div></div></main>}
function Footer({go}:{go:(p:string)=>void}){return <footer><Logo/><p>Красота — это состояние.</p><nav>{nav.map(([l,id])=><button key={id} onClick={()=>go(id)}>{l}</button>)}</nav><div><a href={VK} target="_blank" rel="noreferrer">VK</a><a href="https://t.me/beautyprostranstvo40" target="_blank" rel="noreferrer">Telegram</a></div><small>© {new Date().getFullYear()} Beauty Пространство · Демо‑концепция</small></footer>}
export default function App(){const [page,setPage]=useState(()=>location.hash.slice(1)||'home');useEffect(()=>{const fn=()=>setPage(location.hash.slice(1)||'home');addEventListener('hashchange',fn);return()=>removeEventListener('hashchange',fn)},[]);const go=(p:string)=>{location.hash=p;setPage(p);scrollTo(0,0)};return <><Header page={page} setPage={go}/>{page==='home'&&<Home go={go}/>} {page==='services'&&<Services/>}{page==='works'&&<Works/>}{page==='about'&&<About/>}{page==='contacts'&&<Contacts/>}<Footer go={go}/></>}
