import { FormEvent, PointerEvent, useEffect, useRef, useState } from 'react'
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Camera, Check, ChevronRight, Clock3, MapPin, Maximize2, Menu, MessageCircle, Phone, ShieldCheck, Star, X } from 'lucide-react'
import { benefits, company, projects, reviews, services } from './data/siteConfig'
import { leadService } from './services/leadService'

const nav = [['Услуги','services'],['Работы','works'],['О нас','about'],['Отзывы','reviews'],['Контакты','contacts']]
const smoothTo = (id:string) => document.getElementById(id)?.scrollIntoView({ behavior:'smooth', block:'start' })

function Logo(){ return <button className="logo" onClick={()=>smoothTo('top')} aria-label="На главную"><span className="logo-mark">A</span><span>APEX<small>DETAILING</small></span></button> }

function Header(){
  const [open,setOpen]=useState(false)
  useEffect(()=>{ document.body.classList.toggle('menu-open',open); return()=>document.body.classList.remove('menu-open') },[open])
  useEffect(()=>{ const key=(e:KeyboardEvent)=>e.key==='Escape'&&setOpen(false); addEventListener('keydown',key); return()=>removeEventListener('keydown',key)},[])
  const go=(id:string)=>{setOpen(false); setTimeout(()=>smoothTo(id),10)}
  return <header className="header"><div className="header-inner"><Logo/><nav className="desktop-nav" aria-label="Основная навигация">{nav.map(([l,id])=><button key={id} onClick={()=>go(id)}>{l}</button>)}</nav><button className="header-cta" onClick={()=>go('request')}>Записаться <ArrowUpRight size={16}/></button><button className="menu-button" aria-label="Открыть меню" aria-expanded={open} onClick={()=>setOpen(true)}><Menu/></button></div>
    <div className={`mobile-menu ${open?'is-open':''}`} aria-hidden={!open}><div className="mobile-top"><Logo/><button className="icon-button" aria-label="Закрыть меню" onClick={()=>setOpen(false)}><X/></button></div><nav aria-label="Мобильная навигация">{nav.map(([l,id],i)=><button key={id} onClick={()=>go(id)}><span>0{i+1}</span>{l}<ArrowUpRight/></button>)}</nav><div className="mobile-contact"><a href={company.phoneHref}>{company.phone}</a><span>{company.hours}</span><button className="button primary" onClick={()=>go('request')}>Записаться</button></div></div>
  </header>
}

function Hero(){ return <section className="hero" id="top"><img src="/images/hero.jpg" alt="Премиальный автомобиль в студии APEX DETAILING" className="hero-bg"/><div className="hero-shade"/><div className="hero-content"><div className="eyebrow"><span/> Детейлинг-центр нового уровня · Москва</div><h1>Автомобиль,<br/>к которому хочется<br/><em>обернуться.</em></h1><p>Профессиональный детейлинг, защита кузова и технический уход — в одном центре.</p><div className="hero-actions"><button className="button primary" onClick={()=>smoothTo('request')}>Рассчитать стоимость <ArrowUpRight/></button><button className="button glass" onClick={()=>smoothTo('works')}>Посмотреть работы <ArrowDown/></button></div></div><div className="hero-stats"><div><strong>1 000+</strong><span>автомобилей<br/>обработано</span></div><div><strong>7 лет</strong><span>опыта<br/>команды</span></div><div><ShieldCheck/><span>Гарантия<br/>на работы</span></div></div><div className="hero-scroll">Листайте <span/></div></section> }

function SectionHead({tag,title,aside}:{tag:string,title:React.ReactNode,aside?:string}){return <div className="section-head"><div><div className="eyebrow dark"><span/>{tag}</div><h2>{title}</h2></div>{aside&&<p>{aside}</p>}</div>}

function Services(){return <section className="section services" id="services"><SectionHead tag="Что мы делаем" title={<>Всё для безупречного<br/><em>состояния автомобиля</em></>} aside="От бережной мойки до полной защиты кузова — подбираем решение под задачу, а не продаём лишнее."/><div className="service-grid">{services.map(s=><article className="service-card" key={s.id}><img src={s.image} alt={s.title} loading="lazy" onError={e=>e.currentTarget.classList.add('image-error')}/><div className="service-overlay"/><span className="service-num">{s.n}</span><div className="service-copy"><h3>{s.title}</h3><p>{s.text}</p><div><strong>{s.price}</strong><button onClick={()=>smoothTo('request')} aria-label={`Записаться на ${s.title}`}><ArrowUpRight/></button></div></div></article>)}</div></section>}

function About(){return <section className="section about" id="about"><div className="about-visual"><img src="/images/about.jpg" alt="Мастер APEX DETAILING работает с кузовом автомобиля" loading="lazy"/><div className="about-badge"><strong>7</strong><span>лет создаём<br/>идеальный результат</span></div></div><div className="about-copy"><div className="eyebrow dark"><span/>Почему APEX</div><h2>Забота видна<br/><em>в деталях</em></h2><p className="lead">Относимся к автомобилю как к своему. Перед началом работ фиксируем состояние, согласуем каждый этап и соблюдаем технологию производителя.</p><div className="benefit-list">{benefits.map(b=><div key={b.n}><span>{b.n}</span><div><h3>{b.title}</h3><p>{b.text}</p></div></div>)}</div></div></section>}

function BeforeAfter(){
 const [pos,setPos]=useState(52); const box=useRef<HTMLDivElement>(null)
 const move=(e:PointerEvent)=>{ if(!box.current)return; const r=box.current.getBoundingClientRect(); setPos(Math.max(2,Math.min(98,((e.clientX-r.left)/r.width)*100))) }
 return <section className="before-section"><div className="section narrow"><SectionHead tag="Результат без фильтров" title={<>Разница, которую<br/><em>можно увидеть</em></>} aside="Потяните разделитель — слева исходное состояние лака, справа результат двухэтапной полировки."/><div ref={box} className="compare" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);move(e)}} onPointerMove={e=>e.currentTarget.hasPointerCapture(e.pointerId)&&move(e)}><img src="/images/after.jpg" alt="Кузов после полировки"/><div className="before" style={{width:`${pos}%`}}><img src="/images/before.jpg" alt="Кузов до полировки"/></div><div className="compare-line" style={{left:`${pos}%`}}><button aria-label="Перетащите для сравнения"><ArrowLeft/><ArrowRight/></button></div><span className="compare-label left">До</span><span className="compare-label right">После</span></div></div></section>
}

function Portfolio(){const [active,setActive]=useState<number|null>(null); useEffect(()=>{const k=(e:KeyboardEvent)=>e.key==='Escape'&&setActive(null);addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[]); return <section className="section" id="works"><SectionHead tag="Избранные проекты" title={<>Работы, которыми<br/><em>мы гордимся</em></>} aside="Каждый проект — индивидуальная комбинация технологий, материалов и внимания мастера."/><div className="work-grid">{projects.map((p,i)=><button className={`work-card work-${i+1}`} key={p.car} onClick={()=>setActive(i)}><img src={p.image} alt={`${p.car} — ${p.service}`} loading="lazy"/><div className="work-overlay"/><span>{p.service}</span><div><h3>{p.car}</h3><p>{p.result}</p></div><i><ArrowUpRight/></i></button>)}</div>{active!==null&&<div className="lightbox" role="dialog" aria-modal="true" aria-label={projects[active].car} onMouseDown={e=>e.target===e.currentTarget&&setActive(null)}><button className="lightbox-close" aria-label="Закрыть просмотр" onClick={()=>setActive(null)}><X/></button><img src={projects[active].image} alt={projects[active].car}/><div><span>{projects[active].service}</span><h3>{projects[active].car}</h3><p>{projects[active].result}</p></div></div>}</section>}

function Process(){const steps=['Заявка','Диагностика','Согласование стоимости','Выполнение работ','Приём автомобиля'];return <section className="process"><div className="section"><SectionHead tag="Прозрачный процесс" title={<>От первого сообщения<br/><em>до блеска в глазах</em></>}/><div className="steps">{steps.map((s,i)=><div key={s}><span>0{i+1}</span><h3>{s}</h3><p>{['Уточняем задачу и выбираем удобное время.','Осматриваем автомобиль при правильном свете.','Фиксируем работы, материалы, цену и срок.','Работаем по технологии и сообщаем о прогрессе.','Показываем результат и даём рекомендации.'][i]}</p>{i<4&&<ChevronRight/>}</div>)}</div></div></section>}

function Reviews(){const [page,setPage]=useState(0); return <section className="section reviews" id="reviews"><SectionHead tag="Говорят клиенты" title={<>Доверие, которое<br/><em>мы ценим</em></>}/><div className="review-nav"><span><b>{String(page+1).padStart(2,'0')}</b> / {String(reviews.length).padStart(2,'0')}</span><div><button aria-label="Предыдущий отзыв" onClick={()=>setPage((page-1+reviews.length)%reviews.length)}><ArrowLeft/></button><button aria-label="Следующий отзыв" onClick={()=>setPage((page+1)%reviews.length)}><ArrowRight/></button></div></div><div className="review-stage"><article><div className="stars">{[1,2,3,4,5].map(n=><Star key={n} fill="currentColor"/>)}</div><blockquote>«{reviews[page].text}»</blockquote><div><strong>{reviews[page].name}</strong><span>{reviews[page].car}</span></div></article><div className="review-index">{String(page+1).padStart(2,'0')}</div></div></section>}

function LeadForm(){const [data,setData]=useState({name:'',phone:'',car:'',comment:''});const [errors,setErrors]=useState<Record<string,string>>({});const [status,setStatus]=useState<'idle'|'loading'|'success'>('idle');
 const submit=async(e:FormEvent)=>{e.preventDefault();const er:Record<string,string>={};if(!data.name.trim())er.name='Укажите имя';if(!/^\+?[\d\s()-]{10,}$/.test(data.phone))er.phone='Введите корректный номер телефона';setErrors(er);if(Object.keys(er).length)return;setStatus('loading');await leadService.submit(data);setStatus('success');setData({name:'',phone:'',car:'',comment:''});setTimeout(()=>setStatus('idle'),4500)}
 const field=(key:keyof typeof data,placeholder:string,required=false)=><label><span>{placeholder}{required?' *':''}</span><input name={key} value={data[key]} onChange={e=>{setData({...data,[key]:e.target.value});setErrors({...errors,[key]:''})}} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${key}-error`:undefined}/>{errors[key]&&<small id={`${key}-error`}>{errors[key]}</small>}</label>
 return <section className="request" id="request"><div className="request-copy"><div className="eyebrow"><span/>Персональная консультация</div><h2>Не знаете,<br/>какая услуга <em>нужна?</em></h2><p>Оставьте номер — мастер уточнит задачу, предложит варианты и рассчитает стоимость.</p><div className="request-person"><div>АК</div><p><strong>Александр Крылов</strong><span>Старший мастер-консультант</span></p></div></div><form onSubmit={submit} noValidate>{status==='success'?<div className="success" role="status"><div><Check/></div><h3>Заявка принята</h3><p>Мастер свяжется с вами в рабочее время и уточнит детали.</p><button type="button" onClick={()=>setStatus('idle')}>Отправить ещё одну</button></div>:<><div className="form-row">{field('name','Ваше имя',true)}{field('phone','Телефон',true)}</div>{field('car','Автомобиль')}<label><span>Комментарий</span><textarea name="comment" value={data.comment} onChange={e=>setData({...data,comment:e.target.value})}/></label><button className="button primary submit" disabled={status==='loading'}>{status==='loading'?'Отправляем…':<>Получить расчёт <ArrowUpRight/></>}</button><p className="form-note">Нажимая кнопку, вы соглашаетесь с политикой конфиденциальности</p></>}</form></section>}

function Contacts(){
 const [expanded,setExpanded]=useState(false)
 const mapUrl=`https://yandex.ru/map-widget/v1/?text=${encodeURIComponent(company.address)}&z=15`
 useEffect(()=>{document.body.classList.toggle('menu-open',expanded);return()=>document.body.classList.remove('menu-open')},[expanded])
 useEffect(()=>{const key=(e:KeyboardEvent)=>e.key==='Escape'&&setExpanded(false);addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[])
 const map=<iframe src={mapUrl} title="Интерактивная карта проезда к APEX DETAILING" loading="lazy" allowFullScreen/>
 return <section className="section contacts" id="contacts"><SectionHead tag="Контакты" title={<>Будем рады<br/><em>вашему автомобилю</em></>}/><div className="contact-grid"><div className="contact-main"><a href={company.phoneHref}>{company.phone}</a><p>Позвоните или напишите — ответим на вопросы и подберём удобное время.</p><div><a className="round-link" href={company.telegram} target="_blank" rel="noreferrer" aria-label="Telegram"><MessageCircle/></a><a className="round-link" href={company.whatsapp} target="_blank" rel="noreferrer" aria-label="WhatsApp"><Phone/></a><a className="round-link" href="https://instagram.com" target="_blank" rel="noreferrer" aria-label="Instagram"><Camera/></a></div></div><div className="contact-details"><div><MapPin/><span>Адрес</span><strong>{company.address}</strong></div><div><Clock3/><span>Режим работы</span><strong>{company.hours}</strong></div><a className="button outline" href={company.maps} target="_blank" rel="noreferrer">Построить маршрут <ArrowUpRight/></a></div><div className="map-card">{map}<button className="map-expand" onClick={()=>setExpanded(true)} aria-label="Развернуть карту"><Maximize2/> <span>Развернуть</span></button></div></div>{expanded&&<div className="map-modal" role="dialog" aria-modal="true" aria-label="Карта проезда"><div className="map-modal-bar"><div><strong>APEX DETAILING</strong><span>{company.address}</span></div><a href={company.maps} target="_blank" rel="noreferrer">Маршрут <ArrowUpRight/></a><button onClick={()=>setExpanded(false)} aria-label="Закрыть карту"><X/></button></div>{map}</div>}</section>}

function LegalModal({type,onClose}:{type:'privacy'|'terms',onClose:()=>void}){const close=useRef<HTMLButtonElement>(null);useEffect(()=>{close.current?.focus();const k=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[onClose]);const privacy=type==='privacy';return <div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div><button ref={close} aria-label="Закрыть" onClick={onClose}><X/></button><span>Демонстрационный документ</span><h2 id="modal-title">{privacy?'Политика конфиденциальности':'Пользовательское соглашение'}</h2><p>{privacy?'Мы используем предоставленные вами имя, номер телефона и сведения об автомобиле исключительно для обратной связи по заявке. В демонстрационной версии данные сохраняются только в локальном хранилище вашего браузера и никуда не передаются.':'Сайт является демонстрационным проектом вымышленной компании. Цены и условия указаны для примера и не являются публичной офертой. Отправка формы не создаёт договорных обязательств.'}</p><p>Для настоящего проекта этот текст необходимо заменить документом, подготовленным с учётом фактических процессов компании и требований законодательства.</p><button className="button primary" onClick={onClose}>Понятно</button></div></div>}

function Footer(){const [legal,setLegal]=useState<'privacy'|'terms'|null>(null);return <footer><div className="footer-top"><Logo/><p>Премиальный детейлинг и<br/>технический уход в Москве.</p><nav>{nav.map(([l,id])=><button key={id} onClick={()=>smoothTo(id)}>{l}</button>)}</nav><div><a href={company.phoneHref}>{company.phone}</a><span>{company.hours}</span></div></div><div className="footer-bottom"><span>© 2026 APEX DETAILING</span><div><button onClick={()=>setLegal('privacy')}>Политика конфиденциальности</button><button onClick={()=>setLegal('terms')}>Пользовательское соглашение</button></div><button onClick={()=>smoothTo('top')}>Наверх <ArrowDown/></button></div>{legal&&<LegalModal type={legal} onClose={()=>setLegal(null)}/>}</footer>}

export default function App(){return <><Header/><main><Hero/><Services/><About/><BeforeAfter/><Portfolio/><Process/><Reviews/><LeadForm/><Contacts/></main><Footer/></>}
